import type { APIRoute } from "astro";

const SITE = process.env.SITE_URL ?? `https://${process.env.DOMAIN_NAME ?? "yourdomain.com"}`;

export const GET: APIRoute = () => {
  // Note: sitemap.xml is generated by src/seo/sitemap-builder.ts into public/
  // If size > 50k URLs, sitemap-index.xml is generated instead
  const body = `User-agent: *
Allow: /
Disallow: /api/
Disallow: /admin/

# Crawl-delay: be polite to small server
Crawl-delay: 1

Sitemap: ${SITE}/sitemap.xml
Sitemap: ${SITE}/sitemap-index.xml
`;
  return new Response(body, { headers: { "Content-Type": "text/plain" } });
};
